#!/usr/bin/env bash
# Prints bad luck and good luck on the 4th and 8th iterations.
i="0"

while [ $i -lt 10 ]
do
if (( i == 3)); then
	echo "bad luck"
elif (( i == 7)); then
	echo "good luck"
else
	echo "Best School"
fi
i=$((i+1))
done
