#!/usr/bin/env bash
# Prints info about a file.
if [ -e "school" ];
then
	echo "school file exists"
	if [ -s "school" ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
i	fi
else
	echo "school file does not exist"
fi

if [ -f "school" ];
then
	echo "school is a regular file"
fi
